//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using Engine;
using SBAI;
using SBAIScripts;
using SBBase;
using SBGame;
using SBGamePlay;
using SBMiniGames;
using System;
using System.Collections;
using System.Collections.Generic;
using SBAssemblies;

namespace SBGamePlay
{
    
    
    [System.Serializable] public class EV_SetFaction : Content_Event
    {
        
        [Sirenix.OdinInspector.FoldoutGroup("Action")]
        [FieldConst()]
        public NPC_Taxonomy DesiredFaction;
        
        public EV_SetFaction()
        {
        }
    }
}
/*
function sv_Execute(Game_Pawn aObject,Game_Pawn aSubject) {
if (aSubject != None) {                                                     
aSubject.Character.sv_SetFaction(DesiredFaction);                         
} else {                                                                    
aObject.Character.sv_SetFaction(DesiredFaction);                          
}
}
function bool sv_CanExecute(Game_Pawn aObject,Game_Pawn aSubject) {
return aSubject != None || aObject != None;                                 
}
*/
