//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------



namespace SBAIScripts
{


    public class AIScript_TotA_5_Judge : AIRegistered
    {
        
        public AIScript_TotA_5_Judge()
        {
        }
    }
}
/*
event Trigger(Actor Other,Pawn EventInstigator) {
local RegisteredAI lRegistered;
lRegistered = GetFirstRegistered();                                         
if (lRegistered != None) {                                                  
if (!HasPausedAI(lRegistered.Controller)) {                               
PauseAI(lRegistered.Controller);                                        
}
MoveTo(lRegistered.Controller,EventInstigator.Location);                  
LookAt(lRegistered.Controller,EventInstigator.Location);                  
}
}
*/
