//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;


namespace SBBase
{


    public class DB_Guild : Base_DBObject
    {
        
        public int GroupId;
        
        public int MotdTextId;
        
        public int LogoId;
        
        public int Color1;
        
        public int Color2;
        
        [TCosReborn.Framework.Attributes.FieldConstAttribute()]
        public List<DB_Character> mGuildMembers = new List<DB_Character>();
        
        [TCosReborn.Framework.Attributes.FieldConstAttribute()]
        public bool mGuildMembersSet;
        
        public DB_Guild()
        {
        }
    }
}
