//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using Engine;
using SBAI;
using SBAIScripts;
using SBBase;
using SBGame;
using SBGamePlay;
using SBMiniGames;
using System;
using System.Collections;
using System.Collections.Generic;
using Framework.Attributes;

namespace SBGamePlay
{
    
    
    [System.Serializable] public class QT_Place : Quest_Target
    {
        
        [Sirenix.OdinInspector.FoldoutGroup("Place")]
        [FieldConst()]
        public Content_Inventory Cargo;
        
        [Sirenix.OdinInspector.FoldoutGroup("Place")]
        public NameProperty TargetTag;
        
        [Sirenix.OdinInspector.FoldoutGroup("Place")]
        public LocalizedString TargetDescription;
        
        [Sirenix.OdinInspector.FoldoutGroup("Place")]
        public byte Option;
        
        [Sirenix.OdinInspector.FoldoutGroup("Place")]
        [FieldConst()]
        public int Amount;
        
        public QT_Place()
        {
        }
    }
}
/*
event string GetActiveText(Game_ActiveTextItem aItem) {
if (aItem.Tag == "T") {                                                     
return TargetDescription.Text;                                            
} else {                                                                    
if (aItem.Tag == "O") {                                                   
return Cargo.GetActiveText(aItem.SubItem);                              
} else {                                                                  
if (aItem.Tag == "Q") {                                                 
return "" @ string(Amount);                                           
} else {                                                                
return Super.GetActiveText(aItem);                                    
}
}
}
}
protected function AppendProgressText(out string aDescription,int aProgress) {
if (Amount > 1) {                                                           
}
}
protected function string GetDefaultDescription() {
return Class'StringReferences'.default.QT_PlaceText.Text;                   
}
event RadialMenuCollect(Game_Pawn aPlayerPawn,Object aObject,byte aMainOption,out array<byte> aSubOptions) {
local Actor act;
act = Actor(aObject);                                                       
if (act != None && act.Tag == TargetTag) {                                  
aSubOptions[aSubOptions.Length] = Option;                                 
}
}
*/
