//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;


namespace Engine
{


    public class AmbientSound : Keypoint
    {
        
        [TCosReborn.Framework.Attributes.FieldCategoryAttribute(Category="Sound")]
        public List<SoundEmitter> SoundEmitters = new List<SoundEmitter>();
        
        public float AmbientVolume;
        
        public AmbientSound()
        {
        }
        
        public struct SoundEmitter
        {
            
            public float EmitInterval;
            
            public float EmitVariance;
            
            public float EmitTime;
            
            public Sound EmitSound;
        }
    }
}
