//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using Engine;
using SBAI;
using SBAIScripts;
using SBBase;
using SBGame;
using SBGamePlay;
using SBMiniGames;
using System;
using System.Collections;
using System.Collections.Generic;
using TCosReborn.Framework.Common;


namespace Engine
{
    
    
    public class AnimNotify_DrawWeapon : AnimNotify
    {
        
        [TCosReborn.Framework.Attributes.FieldCategoryAttribute(Category="AnimNotify_DrawWeapon")]
        public NameProperty NotifyName;
        
        [TCosReborn.Framework.Attributes.FieldCategoryAttribute(Category="AnimNotify_DrawWeapon")]
        public byte WeaponFlag;
        
        public AnimNotify_DrawWeapon()
        {
        }
    }
}
