//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using Engine;
using SBAI;
using SBAIScripts;
using SBBase;
using SBGame;
using SBGamePlay;
using SBMiniGames;
using System;
using System.Collections;
using System.Collections.Generic;
using TCosReborn.Framework.Common;


namespace Engine
{
    
    
    public class Client : UObject
    {
        
        [TCosReborn.Framework.Attributes.FieldConfigAttribute()]
        public bool CaptureMouse;
        
        [TCosReborn.Framework.Attributes.FieldConfigAttribute()]
        public bool ScreenFlashes;
        
        [TCosReborn.Framework.Attributes.FieldConfigAttribute()]
        public bool NoLighting;
        
        [TCosReborn.Framework.Attributes.FieldConfigAttribute()]
        public bool Decals;
        
        [TCosReborn.Framework.Attributes.FieldConfigAttribute()]
        public bool NoDynamicLights;
        
        [TCosReborn.Framework.Attributes.FieldConfigAttribute()]
        public bool NoFractalAnim;
        
        [TCosReborn.Framework.Attributes.FieldConfigAttribute()]
        public bool Coronas;
        
        [TCosReborn.Framework.Attributes.FieldConfigAttribute()]
        public bool DecoLayers;
        
        [TCosReborn.Framework.Attributes.FieldConfigAttribute()]
        public bool Projectors;
        
        [TCosReborn.Framework.Attributes.FieldConfigAttribute()]
        public bool ReportDynamicUploads;
        
        [TCosReborn.Framework.Attributes.FieldConfigAttribute()]
        public bool WeatherEffects;
        
        [TCosReborn.Framework.Attributes.FieldConfigAttribute()]
        public int WindowedViewportX;
        
        [TCosReborn.Framework.Attributes.FieldConfigAttribute()]
        public int WindowedViewportY;
        
        [TCosReborn.Framework.Attributes.FieldConfigAttribute()]
        public int FullscreenViewportX;
        
        [TCosReborn.Framework.Attributes.FieldConfigAttribute()]
        public int FullscreenViewportY;
        
        [TCosReborn.Framework.Attributes.FieldConfigAttribute()]
        public int MenuViewportX;
        
        [TCosReborn.Framework.Attributes.FieldConfigAttribute()]
        public int MenuViewportY;
        
        [TCosReborn.Framework.Attributes.FieldConfigAttribute()]
        public float Brightness;
        
        [TCosReborn.Framework.Attributes.FieldConfigAttribute()]
        public float Contrast;
        
        [TCosReborn.Framework.Attributes.FieldConfigAttribute()]
        public float Gamma;
        
        [TCosReborn.Framework.Attributes.FieldConfigAttribute()]
        public byte TextureDetailWorld;
        
        [TCosReborn.Framework.Attributes.FieldConfigAttribute()]
        public byte TextureDetailPlayerSkin;
        
        [TCosReborn.Framework.Attributes.FieldConfigAttribute()]
        public byte TextureDetailWeaponSkin;
        
        [TCosReborn.Framework.Attributes.FieldConfigAttribute()]
        public byte TextureDetailTerrain;
        
        [TCosReborn.Framework.Attributes.FieldConfigAttribute()]
        public byte TextureDetailInterface;
        
        [TCosReborn.Framework.Attributes.FieldConfigAttribute()]
        public byte TextureDetailRenderMap;
        
        [TCosReborn.Framework.Attributes.FieldConfigAttribute()]
        public byte TextureDetailLightmap;
        
        [TCosReborn.Framework.Attributes.FieldConfigAttribute()]
        public float MinDesiredFrameRate;
        
        [TCosReborn.Framework.Attributes.FieldConfigAttribute()]
        public float ScaleHUDX;
        
        [TCosReborn.Framework.Attributes.FieldConfigAttribute()]
        public float AnimMeshDynamicLOD;
        
        [TCosReborn.Framework.Attributes.FieldConfigAttribute()]
        public float DrawDistanceLOD;
        
        public Client()
        {
        }
    }
}
