//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using Engine;
using SBAI;
using SBAIScripts;
using SBBase;
using SBGame;
using SBGamePlay;
using SBMiniGames;
using System;
using System.Collections;
using System.Collections.Generic;
using TCosReborn.Framework.Common;


namespace Engine
{
    
    
    public class EnvironmentManager : Actor
    {
        
        private List<ZoneInfo> mZoneInfos = new List<ZoneInfo>();
        
        private List<Light> mLights = new List<Light>();
        
        private List<ParticleEmitter> mEmitters = new List<ParticleEmitter>();
        
        private List<EnvironmentEffect> mEffects = new List<EnvironmentEffect>();
        
        private EnvironmentSettings mCurrentSettings;
        
        [TCosReborn.Framework.Attributes.IgnoreFieldExtractionAttribute()]
        private Color mDefaultColor;
        
        public EnvironmentManager()
        {
        }
    }
}
/*
final native function SetDefaultHUDColor(Color aColor);
event PostBeginPlay() {
if (IsServer() || IsEditor()) {                                             
return;                                                                   
}
SetDrawType(0);                                                             
BuildListOfEnvironmentActors();                                             
}
final native function AddEffect(EnvironmentEffect effect);
final native function BuildListOfEnvironmentActors();
*/
