//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using Engine;
using SBAI;
using SBAIScripts;
using SBBase;
using SBGame;
using SBGamePlay;
using SBMiniGames;
using System;
using System.Collections;
using System.Collections.Generic;
using TCosReborn.Framework.Common;


namespace Engine
{
    
    
    public class SBDecoMaterial : SBMaterial
    {
        
        [TCosReborn.Framework.Attributes.FieldCategoryAttribute(Category="SBDecoMaterial")]
        public float LightmapContrastAdjust;
        
        [TCosReborn.Framework.Attributes.FieldCategoryAttribute(Category="SBDecoMaterial")]
        public float SunlightsContrastAdjust;
        
        [TCosReborn.Framework.Attributes.FieldCategoryAttribute(Category="SBDecoMaterial")]
        public float SunlightsBrightness;
        
        [TCosReborn.Framework.Attributes.FieldCategoryAttribute(Category="SBDecoMaterial")]
        [TCosReborn.Framework.Attributes.IgnoreFieldExtractionAttribute()]
        public Material Material;
        
        [TCosReborn.Framework.Attributes.FieldCategoryAttribute(Category="SBDecoMaterial")]
        public Range FadeinRadius;
        
        [TCosReborn.Framework.Attributes.FieldCategoryAttribute(Category="SBDecoMaterial")]
        public Range FadeoutRadius;
        
        [TCosReborn.Framework.Attributes.FieldCategoryAttribute(Category="SBDecoMaterial")]
        public float CoordinateScale;
        
        public SBDecoMaterial()
        {
        }
    }
}
