//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Engine
{


    public class SubActionFade : MatSubAction
    {
        
        [TCosReborn.Framework.Attributes.FieldCategoryAttribute(Category="Fade")]
        [TCosReborn.Framework.Attributes.IgnoreFieldExtractionAttribute()]
        public Color FadeColor;
        
        [TCosReborn.Framework.Attributes.FieldCategoryAttribute(Category="Fade")]
        public bool bFadeOut;
        
        public SubActionFade()
        {
        }
    }
}
