//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;


namespace Engine
{


    public class TerrainMaterial : RenderedMaterial
    {
        
        [TCosReborn.Framework.Attributes.FieldConstAttribute()]
        public List<TerrainMaterialLayer> Layers = new List<TerrainMaterialLayer>();
        
        [TCosReborn.Framework.Attributes.FieldConstAttribute()]
        public byte RenderMethod;
        
        [TCosReborn.Framework.Attributes.FieldConstAttribute()]
        public bool FirstPass;
        
        public TerrainMaterial()
        {
        }
        
        public struct TerrainMaterialLayer
        {
            
            public Material Texture;
            
            public BitmapMaterial AlphaWeight;
            
            public Matrix TextureMatrix;
        }
    }
}
