//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Engine
{


    public class TexCoordSource : TexModifier
    {
        
        [TCosReborn.Framework.Attributes.FieldCategoryAttribute(Category="TexCoordSource")]
        public int SourceChannel;
        
        public TexCoordSource()
        {
        }
    }
}
