//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Engine
{


    public class TexPannerTriggered : TexPanner
    {
        
        [TCosReborn.Framework.Attributes.FieldCategoryAttribute(Category="TexPannerTriggered")]
        public byte RetriggerAction;
        
        [TCosReborn.Framework.Attributes.FieldCategoryAttribute(Category="TexPannerTriggered")]
        public float StopAfterPeriod;
        
        [TCosReborn.Framework.Attributes.IgnoreFieldExtractionAttribute()]
        [TCosReborn.Framework.Attributes.FieldTransientAttribute()]
        public float TriggeredTime;
        
        [TCosReborn.Framework.Attributes.IgnoreFieldExtractionAttribute()]
        [TCosReborn.Framework.Attributes.FieldTransientAttribute()]
        public bool Reverse;
        
        [TCosReborn.Framework.Attributes.IgnoreFieldExtractionAttribute()]
        [TCosReborn.Framework.Attributes.FieldTransientAttribute()]
        public bool Triggered;
        
        public TexPannerTriggered()
        {
        }
    }
}
/*
function Reset() {
Triggered = False;                                                          
TriggeredTime = -1.00000000;                                                
Reverse = False;                                                            
}
function Trigger(Actor Other,Actor EventInstigator) {
if (Triggered) {                                                            
switch (RetriggerAction) {                                                
case 0 :                                                                
Triggered = False;                                                    
TriggeredTime = Other.Level.TimeSeconds;                              
Reverse = True;                                                       
break;                                                                
case 1 :                                                                
Triggered = False;                                                    
TriggeredTime = -1.00000000;                                          
Reverse = True;                                                       
break;                                                                
default:                                                                
}
} else {                                                                    
if (RetriggerAction != 3) {                                               
Triggered = True;                                                       
}
TriggeredTime = Other.Level.TimeSeconds;                                  
Reverse = False;                                                          
}
}
*/
