//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------



namespace Engine
{


    public class VariableTexPanner : TexModifier
    {
        
        [TCosReborn.Framework.Attributes.FieldCategoryAttribute(Category="VariableTexPanner")]
        public Rotator PanDirection;
        
        [TCosReborn.Framework.Attributes.FieldCategoryAttribute(Category="VariableTexPanner")]
        public float PanRate;
        
        [TCosReborn.Framework.Attributes.IgnoreFieldExtractionAttribute()]
        public Matrix M;
        
        public float LastTime;
        
        public float PanOffset;
        
        public VariableTexPanner()
        {
        }
    }
}
