//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using Engine;
using SBAI;
using SBAIScripts;
using SBBase;
using SBGame;
using SBGamePlay;
using SBMiniGames;
using System;
using System.Collections;
using System.Collections.Generic;

namespace SBBase
{
    
    
    [System.Serializable] public class Base_Notification : UObject
    {
        
        public int mNotificationData;
        
        public Base_Notification()
        {
        }
    }
}
/*
final native function RemoveListener(Object Object);
final native function AddListener(Object Object,name funcName);
native function Delete();
*/
