//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using Engine;
using SBAI;
using SBAIScripts;
using SBBase;
using SBGame;
using SBGamePlay;
using SBMiniGames;
using System;
using System.Collections;
using System.Collections.Generic;
using Framework.Attributes;

namespace SBGame
{
    
    
    [System.Serializable] public class AnnotationActor : SBPoint
    {
        
        [FieldCategory(Category="Annotation")]
        public byte AnnotationType;
        
        [FieldCategory(Category="Annotation")]
        public bool CreateNode;
        
        [FieldCategory(Category="Annotation")]
        public Vector Extent;
        
        [FieldCategory(Category="Annotation")]
        public bool FitNode;
        
        [FieldCategory(Category="Annotation")]
        public List<byte> AnnotationMask = new List<byte>();
        
        [IgnoreFieldExtraction()]
        [FieldTransient()]
        public int OriginCell;
        
        [IgnoreFieldExtraction()]
        [FieldTransient()]
        public bool AccessmapLinked;
        
        [IgnoreFieldExtraction()]
        [FieldTransient()]
        public int mInstances;
        
        public AnnotationActor()
        {
        }
    }
}
