//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using Engine;
using SBAI;
using SBAIScripts;
using SBBase;
using SBGame;
using SBGamePlay;
using SBMiniGames;
using System;
using System.Collections;
using System.Collections.Generic;
using Framework.Attributes;

namespace SBGame
{
    
    
    [System.Serializable] public class FSkill_Event_Duff_CondEv : UObject
    {
        
        [FieldCategory(Category="CondEv")]
        [FieldConst()]
        public FSkill_Event Event;
        
        [FieldCategory(Category="CondEv")]
        [FieldConst()]
        public int Uses;
        
        [FieldCategory(Category="CondEv")]
        [FieldConst()]
        public int MaximumTriggersPerUse;
        
        [FieldCategory(Category="CondEv")]
        [FieldConst()]
        public float Interval;
        
        [FieldCategory(Category="CondEv")]
        [FieldConst()]
        public float Delay;
        
        [FieldCategory(Category="CondEv")]
        [FieldConst()]
        public float IncreasePerUse;
        
        [FieldCategory(Category="CondEv")]
        [FieldConst()]
        public byte Condition;
        
        [FieldCategory(Category="CondEv")]
        [FieldConst()]
        public byte AttackType;
        
        [FieldCategory(Category="CondEv")]
        [FieldConst()]
        public byte MagicType;
        
        [FieldCategory(Category="CondEv")]
        [FieldConst()]
        public byte EffectType;
        
        [FieldCategory(Category="CondEv")]
        [FieldConst()]
        public byte Target;
        
        [IgnoreFieldExtraction()]
        [FieldTransient()]
        public bool Running;
        
        public FSkill_Event_Duff_CondEv()
        {
        }
    }
}
