//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using Engine;
using SBAI;
using SBAIScripts;
using SBBase;
using SBGame;
using SBGamePlay;
using SBMiniGames;
using System;
using System.Collections;
using System.Collections.Generic;
using Framework.Attributes;

namespace SBGame
{
    
    
    [System.Serializable] public class Game_GameServer : Base_GameServer
    {
        
        public int FActorStatsWindowDummy1;
        
        public int FActorStatsWindowDummy2;
        
        public int FActorInspectInterfaceDummy1;
        
        public int FActorInspectInterfaceDummy2;
        
        public int FMemoryStatsWindowDummy1;
        
        public int FMemoryStatsWindowDummy2;
        
        [IgnoreFieldExtraction()]
        [FieldTransient()]
        public int FPathplanningWindowDummy1;
        
        [IgnoreFieldExtraction()]
        [FieldTransient()]
        public int FPathplanningWindowDummy2;
        
        public Game_GameServer()
        {
        }
    }
}
