//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using Engine;
using SBAI;
using SBAIScripts;
using SBBase;
using SBGame;
using SBGamePlay;
using SBMiniGames;
using System;
using System.Collections;
using System.Collections.Generic;

namespace SBGame
{
    
    
    [System.Serializable] public class Game_EmoteRotate : Game_Emote
    {
        
        public int Yaw;
        
        public Game_EmoteRotate()
        {
        }
    }
}
/*
function OnClientExecute(Game_Pawn aPawn) {
Super.OnClientExecute(aPawn);                                               
}
function OnServerExecute(Game_Pawn aPawn) {
local Rotator DesiredRotation;
DesiredRotation.Yaw = Yaw;                                                  
Super.OnServerExecute(aPawn);                                               
aPawn.SetRotation(DesiredRotation);                                         
if (aPawn.IsPlayerPawn()) {                                                 
aPawn.sv_TeleportTo(aPawn.Location,DesiredRotation);                      
} else {                                                                    
aPawn.sv_TeleportTo(aPawn.Location,DesiredRotation);                      
}
}
*/
