//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using Engine;
using SBAI;
using SBAIScripts;
using SBBase;
using SBGame;
using SBGamePlay;
using SBMiniGames;
using System;
using System.Collections;
using System.Collections.Generic;
using Framework.Attributes;

namespace Engine
{
    
    
    [System.Serializable] public class Light : Actor
    {
        
        [Sirenix.OdinInspector.FoldoutGroup("Corona")]
        public float MinCoronaSize;
        
        [Sirenix.OdinInspector.FoldoutGroup("Corona")]
        public float MaxCoronaSize;
        
        [Sirenix.OdinInspector.FoldoutGroup("Corona")]
        public float CoronaRotation;
        
        [Sirenix.OdinInspector.FoldoutGroup("Corona")]
        public float CoronaRotationOffset;
        
        [Sirenix.OdinInspector.FoldoutGroup("Corona")]
        public bool UseOwnFinalBlend;
        
        [Sirenix.OdinInspector.FoldoutGroup("Lighting")]
        public byte LightShadingEffect;
        
        public byte DayLightCycleLightIndex;
        
        [Sirenix.OdinInspector.FoldoutGroup("Environment")]
        public byte EnvironmentIndex;
        
        [Sirenix.OdinInspector.FoldoutGroup("Lightmap")]
        public float ProjectorBrightness;
        
        [Sirenix.OdinInspector.FoldoutGroup("Lightmap")]
        public float LightmapBlur;
        
        [FieldConst()]
        [System.NonSerialized, UnityEngine.HideInInspector]
        [FieldTransient()]
        public SBShadowMap ShadowMap;
        
        public Light()
        {
        }
        
        public enum ELightIndex
        {
            
            LI_NONE ,
            
            LI_LIGHT0 ,
            
            LI_LIGHT1 ,
            
            LI_LIGHT2 ,
            
            LI_LIGHT3 ,
            
            LI_LIGHT4 ,
            
            LI_LIGHT5 ,
            
            LI_LIGHT6 ,
            
            LI_LIGHT7,
        }
        
        public enum ELightShadingEffect
        {
            
            LSE_Default ,
            
            LSE_NoShadows ,
            
            LSE_NoShading,
        }
    }
}
