//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using SBGame;


namespace SBGamePlay
{


    public class EV_Self : Content_Event
    {
        
        [TCosReborn.Framework.Attributes.FieldCategoryAttribute(Category="Action")]
        [TCosReborn.Framework.Attributes.FieldConstAttribute()]
        public Content_Event SelfAction;
        
        public EV_Self()
        {
        }
    }
}
/*
function sv_Execute(Game_Pawn aObject,Game_Pawn aSubject) {
SelfAction.sv_Execute(aObject,aObject);                                     
}
function bool sv_CanExecute(Game_Pawn aObject,Game_Pawn aSubject) {
if (SelfAction != None) {                                                   
return SelfAction.sv_CanExecute(aObject,aObject);                         
}
return False;                                                               
}
*/
