//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using SBGame;


namespace SBGamePlay
{


    public class EV_Scenario : Content_Event
    {
        
        [TCosReborn.Framework.Attributes.FieldCategoryAttribute(Category="Action")]
        public string ScenarioTag = string.Empty;
        
        public EV_Scenario()
        {
        }
    }
}
/*
function sv_Execute(Game_Pawn anObject,Game_Pawn aSubject) {
local export editinline Scenario aScenario;
aScenario = Scenario(static.DynamicLoadObject(ScenarioTag,Class'Scenario'));
aScenario.ForwardEvents(anObject);                                          
}
function bool sv_CanExecute(Game_Pawn aObject,Game_Pawn aSubject) {
local export editinline Scenario aScenario;
aScenario = Scenario(static.DynamicLoadObject(ScenarioTag,Class'Scenario'));
if (aScenario != None
&& aScenario.VerifyRequirements(aObject)) {     
return True;                                                              
}
return False;                                                               
}
*/
