//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using SBGame;
using System.Collections.Generic;


namespace SBGamePlay
{


    public class QC_Stealth : Quest_Condition
    {
        
        [TCosReborn.Framework.Attributes.FieldCategoryAttribute(Category="Condition")]
        [TCosReborn.Framework.Attributes.FieldConstAttribute()]
        public List<NPC_Type> NamedTargets = new List<NPC_Type>();
        
        [TCosReborn.Framework.Attributes.FieldCategoryAttribute(Category="Condition")]
        [TCosReborn.Framework.Attributes.FieldConstAttribute()]
        public List<NPC_Taxonomy> GroupedTargets = new List<NPC_Taxonomy>();
        
        public QC_Stealth()
        {
        }
    }
}
/*
protected function string GetDefaultDescription() {
return Class'StringReferences'.default.QC_StealthText.Text;                 
}
*/
