//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using SBGame;


namespace SBGamePlay
{


    public class QR_Fame : Quest_Reward
    {
        
        [TCosReborn.Framework.Attributes.FieldCategoryAttribute(Category="reward")]
        [TCosReborn.Framework.Attributes.FieldConstAttribute()]
        public int Fame;
        
        public QR_Fame()
        {
        }
    }
}
/*
function string GetText() {
return string(Fame)
@ Class'SBGamePlayStrings'.default.Fame.Text;     
}
*/
