//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using SBGame;


namespace SBGamePlay
{


    public class Req_PersistentValue : Content_Requirement
    {
        
        public Content_Type context;
        
        [TCosReborn.Framework.Attributes.FieldCategoryAttribute(Category="Requirement")]
        public int VariableID;
        
        [TCosReborn.Framework.Attributes.FieldCategoryAttribute(Category="Requirement")]
        public int Value;
        
        [TCosReborn.Framework.Attributes.FieldCategoryAttribute(Category="Requirement")]
        [TCosReborn.Framework.Attributes.FieldConstAttribute()]
        public byte Operator;
        
        public Req_PersistentValue()
        {
        }
    }
}
/*
function bool ApiTracing() {
return True;                                                                
}
*/
