//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using Engine;
using SBGame;
using System.Collections.Generic;
using TCosReborn.Framework.Common;


namespace SBGamePlay
{


    public class Spawn_Triggered : Spawn_Area
    {
        
        [TCosReborn.Framework.Attributes.IgnoreFieldExtractionAttribute()]
        [TCosReborn.Framework.Attributes.FieldTransientAttribute()]
        public Vector SpawnerLocation;
        
        [TCosReborn.Framework.Attributes.IgnoreFieldExtractionAttribute()]
        [TCosReborn.Framework.Attributes.FieldTransientAttribute()]
        public SpawnConfig CurrentlySpawning;
        
        [TCosReborn.Framework.Attributes.IgnoreFieldExtractionAttribute()]
        [TCosReborn.Framework.Attributes.FieldTransientAttribute()]
        public int WaveCount;
        
        [TCosReborn.Framework.Attributes.FieldCategoryAttribute(Category="Spawn")]
        public List<SpawnConfig> SpawnerConfig = new List<SpawnConfig>();
        
        [TCosReborn.Framework.Attributes.FieldCategoryAttribute(Category="Spawn")]
        public float MinSpawnsPerWave;
        
        [TCosReborn.Framework.Attributes.FieldCategoryAttribute(Category="Spawn")]
        public float MaxSpawnsPerWave;
        
        [TCosReborn.Framework.Attributes.FieldCategoryAttribute(Category="Spawn")]
        public float MaxSpawnsAlive;
        
        [TCosReborn.Framework.Attributes.FieldCategoryAttribute(Category="Spawn")]
        public float MaxWaves;
        
        [TCosReborn.Framework.Attributes.FieldCategoryAttribute(Category="Spawn")]
        public bool UseChanceAsCount;
        
        [TCosReborn.Framework.Attributes.FieldCategoryAttribute(Category="aI")]
        [TCosReborn.Framework.Attributes.TypeProxyDefinition(TypeName="AIStateMachine")]
        public SerializableTypeProxy StateMachine;
        
        public Spawn_Triggered()
        {
        }
        
        public struct SpawnConfig
        {
            
            public NPC_Type NPCType;
            
            public NPC_Taxonomy Faction;
            
            public int Chance;
            
            public int MinLevel;
            
            public int MaxLevel;
            
            public int PePRank;
        }
    }
}
/*
function sv_Despawn() {
local int is;
is = 0;                                                                     
while (is < Spawns.Length) {                                                
Spawns[is].sv_Despawn();                                                  
Spawns[is] = None;                                                        
is++;                                                                     
}
Spawns.Length = 0;                                                          
}
function PostBeginPlay() {
local int i;
i = 0;                                                                      
while (i < SpawnerConfig.Length) {                                          
i++;                                                                      
}
Super.PostBeginPlay();                                                      
}
*/
