//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------



namespace SBGamePlay
{


    public class Spawn_Placed : Spawn_Triggered
    {
        
        [TCosReborn.Framework.Attributes.FieldCategoryAttribute(Category="Spawn_Placed")]
        public bool UseRandomLocation;
        
        public Spawn_Placed()
        {
        }
    }
}
