//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using SBBase;


namespace SBGame
{


    public class Editor_SpwnieControl : Base_Component
    {
        
        public Editor_Spwnie mTarget;
        
        public Editor_SpwnieControl()
        {
        }
    }
}
/*
function SetTarget(Editor_Spwnie aTarget) {
if (mTarget != None) {                                                      
mTarget.SetSelected(False);                                               
}
mTarget = aTarget;                                                          
if (mTarget != None) {                                                      
mTarget.SetSelected(True);                                                
}
}
*/
