//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using TCosReborn.Framework.Common;


namespace SBGame
{


    public class FSkill_Event_Duff_DirectEff : SBPackageResource
    {
        
        [TCosReborn.Framework.Attributes.FieldConstAttribute()]
        public FSkill_EffectClass_Direct effect;
        
        [TCosReborn.Framework.Attributes.FieldCategoryAttribute(Category="DirectEff")]
        [TCosReborn.Framework.Attributes.FieldConstAttribute()]
        public float Interval;
        
        [TCosReborn.Framework.Attributes.FieldCategoryAttribute(Category="DirectEff")]
        [TCosReborn.Framework.Attributes.FieldConstAttribute()]
        public float Delay;
        
        [TCosReborn.Framework.Attributes.FieldCategoryAttribute(Category="DirectEff")]
        [TCosReborn.Framework.Attributes.FieldConstAttribute()]
        public int RepeatCount;
        
        [TCosReborn.Framework.Attributes.FieldConstAttribute()]
        public FSkill_Event_FX ExecuteFXEvent;
        
        public FSkill_Event_Duff_DirectEff()
        {
        }
    }
}
