//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Collections.Generic;


namespace SBGame
{


    public class FSkill_Event_Target : FSkill_Event_FX
    {
        
        [TCosReborn.Framework.Attributes.FieldCategoryAttribute(Category="Target")]
        [TCosReborn.Framework.Attributes.FieldConstAttribute()]
        public int MaxTargets;
        
        [TCosReborn.Framework.Attributes.FieldCategoryAttribute(Category="Target")]
        [TCosReborn.Framework.Attributes.FieldConstAttribute()]
        public byte TargetBase;
        
        [TCosReborn.Framework.Attributes.FieldCategoryAttribute(Category="Target")]
        [TCosReborn.Framework.Attributes.FieldConstAttribute()]
        public byte TargetSelf;
        
        [TCosReborn.Framework.Attributes.FieldCategoryAttribute(Category="Target")]
        [TCosReborn.Framework.Attributes.FieldConstAttribute()]
        public byte TargetEnemies;
        
        [TCosReborn.Framework.Attributes.FieldCategoryAttribute(Category="Target")]
        [TCosReborn.Framework.Attributes.FieldConstAttribute()]
        public byte TargetFriendlies;
        
        [TCosReborn.Framework.Attributes.FieldConstAttribute()]
        public byte TargetNeutrals;
        
        [TCosReborn.Framework.Attributes.FieldCategoryAttribute(Category="Target")]
        [TCosReborn.Framework.Attributes.FieldConstAttribute()]
        public byte TargetSpirits;
        
        [TCosReborn.Framework.Attributes.FieldCategoryAttribute(Category="Target")]
        [TCosReborn.Framework.Attributes.FieldConstAttribute()]
        public byte TargetBloodlinks;
        
        [TCosReborn.Framework.Attributes.FieldCategoryAttribute(Category="Target")]
        [TCosReborn.Framework.Attributes.FieldConstAttribute()]
        public byte TargetPartyMembers;
        
        [TCosReborn.Framework.Attributes.FieldCategoryAttribute(Category="Target")]
        [TCosReborn.Framework.Attributes.FieldConstAttribute()]
        public byte TargetGuildMembers;
        
        [TCosReborn.Framework.Attributes.FieldCategoryAttribute(Category="Target")]
        [TCosReborn.Framework.Attributes.FieldConstAttribute()]
        public byte TargetPets;
        
        [TCosReborn.Framework.Attributes.FieldCategoryAttribute(Category="Target")]
        [TCosReborn.Framework.Attributes.FieldConstAttribute()]
        public List<NPC_Taxonomy> LimitToTaxonomy = new List<NPC_Taxonomy>();
        
        [TCosReborn.Framework.Attributes.FieldCategoryAttribute(Category="Target")]
        [TCosReborn.Framework.Attributes.FieldConstAttribute()]
        public bool TargetAttached;
        
        [TCosReborn.Framework.Attributes.IgnoreFieldExtractionAttribute()]
        [TCosReborn.Framework.Attributes.FieldTransientAttribute()]
        private bool DidNeedRangeCheck;
        
        [TCosReborn.Framework.Attributes.IgnoreFieldExtractionAttribute()]
        [TCosReborn.Framework.Attributes.FieldTransientAttribute()]
        private bool DidHasAutoTargets;
        
        [TCosReborn.Framework.Attributes.IgnoreFieldExtractionAttribute()]
        [TCosReborn.Framework.Attributes.FieldTransientAttribute()]
        private bool ResultNeedRangeCheck;
        
        [TCosReborn.Framework.Attributes.IgnoreFieldExtractionAttribute()]
        [TCosReborn.Framework.Attributes.FieldTransientAttribute()]
        private bool ResultHasAutoTargets;
        
        public FSkill_Event_Target()
        {
        }
    }
}
