//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------



namespace SBGame
{


    public class Game_StatueCharacter : Game_Character
    {
        
        public Game_StatueCharacter()
        {
        }
    }
}
/*
event string cl_GetBaseFullName() {
return Outer.PlayerName;                                                    
}
event string cl_GetBaseName() {
return Outer.PlayerName;                                                    
}
*/
