//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using TCosReborn.Framework.Common;


namespace SBGame
{


    public class Game_HUD : SBPackageResource
    {
        
        public Game_HUD()
        {
        }
    }
}
/*
native event Destroyed();
final native function cl_OnInit();
final native function cl_AddScrollingCombatMessage(string aText,byte aType,optional float aExtraScale);
*/
