//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using Engine;
using SBAI;
using SBAIScripts;
using SBBase;
using SBGame;
using SBGamePlay;
using SBMiniGames;
using System;
using System.Collections;
using System.Collections.Generic;
using TCosReborn.Framework.Common;


namespace SBGame
{
    
    
    public class NPC_SkillCondition_Targets : NPC_SkillCondition_Self
    {
        
        [TCosReborn.Framework.Attributes.FieldCategoryAttribute(Category="Misc")]
        public bool DistanceCheck;
        
        [TCosReborn.Framework.Attributes.FieldCategoryAttribute(Category="Misc")]
        public bool AliveCheck;
        
        [TCosReborn.Framework.Attributes.FieldCategoryAttribute(Category="Misc")]
        public byte DistanceOperator;
        
        [TCosReborn.Framework.Attributes.FieldCategoryAttribute(Category="PMC")]
        public byte PhysiqueContext;
        
        [TCosReborn.Framework.Attributes.FieldCategoryAttribute(Category="PMC")]
        public byte MoraleContext;
        
        [TCosReborn.Framework.Attributes.FieldCategoryAttribute(Category="PMC")]
        public byte ConcentrationContext;
        
        [TCosReborn.Framework.Attributes.FieldCategoryAttribute(Category="BMF")]
        public byte BodyContext;
        
        [TCosReborn.Framework.Attributes.FieldCategoryAttribute(Category="BMF")]
        public byte MindContext;
        
        [TCosReborn.Framework.Attributes.FieldCategoryAttribute(Category="BMF")]
        public byte FocusContext;
        
        [TCosReborn.Framework.Attributes.FieldCategoryAttribute(Category="Misc")]
        public byte HealthContext;
        
        [TCosReborn.Framework.Attributes.FieldCategoryAttribute(Category="Misc")]
        public byte MovementFrozenContext;
        
        [TCosReborn.Framework.Attributes.FieldCategoryAttribute(Category="Misc")]
        public byte RotationFrozenContext;
        
        [TCosReborn.Framework.Attributes.FieldCategoryAttribute(Category="Misc")]
        public byte DistanceContext;
        
        [TCosReborn.Framework.Attributes.FieldCategoryAttribute(Category="Misc")]
        public float DistanceValue;
        
        public NPC_SkillCondition_Targets()
        {
        }
        
        public enum ETargetContext
        {
            
            ETC_AnyFriendlyTarget ,
            
            ETC_AnyEnemyTarget ,
            
            ETC_AverageFriendlyTargets ,
            
            ETC_AverageEnemyTargets,
        }
    }
}
