//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using Engine;
using SBAI;
using SBAIScripts;
using SBBase;
using SBGame;
using SBGamePlay;
using SBMiniGames;
using System;
using System.Collections;
using System.Collections.Generic;
using Framework.Attributes;

namespace SBGame
{
    
    
    [System.Serializable] public class AccessmapStartPoint : NavigationPoint
    {
        
        [Sirenix.OdinInspector.FoldoutGroup("AccessmapStartPoint")]
        public Vector extend;
        
        [Sirenix.OdinInspector.FoldoutGroup("Debug")]
        public bool IsActive;
        
        public AccessmapStartPoint()
        {
        }
    }
}
