//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using Engine;
using SBAI;
using SBAIScripts;
using SBBase;
using SBGame;
using SBGamePlay;
using SBMiniGames;
using System;
using System.Collections;
using System.Collections.Generic;

namespace SBGame
{
    
    
    [System.Serializable] public class StateListener : UObject
    {
        
        //public delegate<OnStateBegin> @__OnStateBegin__Delegate;
        
        //public delegate<OnStateEnd> @__OnStateEnd__Delegate;
        
        //public delegate<OnStateCancel> @__OnStateCancel__Delegate;
        
        public StateListener()
        {
        }
    }
}
/*
delegate OnStateCancel(name aStateName);
delegate OnStateEnd(name aStateName);
delegate OnStateBegin(name aStateName);
*/
