//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using Engine;
using SBAI;
using SBAIScripts;
using SBBase;
using SBGame;
using SBGamePlay;
using SBMiniGames;
using System;
using System.Collections;
using System.Collections.Generic;

namespace SBGamePlay
{
    
    
    [System.Serializable] public class QC_Survival : Quest_Condition
    {
        
        [Sirenix.OdinInspector.FoldoutGroup("Survival")]
        [FieldConst()]
        public float DefeatFraction;
        
        public QC_Survival()
        {
        }
    }
}
/*
protected function string GetDefaultDescription() {
return Class'StringReferences'.default.QC_SurvivalText.Text;                
}
*/
