//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using Engine;
using SBAI;
using SBAIScripts;
using SBBase;
using SBGame;
using SBGamePlay;
using SBMiniGames;
using System;
using System.Collections;
using System.Collections.Generic;
using Framework.Attributes;

namespace SBGamePlay
{
    
    
    [System.Serializable] public class NA_Equipped : NA_RaceBodyGender
    {
        
        [FieldCategory(Category="Decoration")]
        [FieldConst()]
        public int Head;
        
        [FieldCategory(Category="Decoration")]
        [FieldConst()]
        public Appearance_Hair Hair;
        
        [FieldCategory(Category="Colour")]
        [FieldConst()]
        public byte BodyColor;
        
        [FieldCategory(Category="Colour")]
        [FieldConst()]
        public byte HairColor;
        
        [FieldCategory(Category="Effects")]
        public bool Ghostly;
        
        [FieldCategory(Category="Effects")]
        public bool Statue;
        
        public NA_Equipped()
        {
        }
    }
}
/*
event int GetHead() {
return Head;                                                                
}
event SetHead(int NewHead) {
Head = NewHead;                                                             
}
function Game_Appearance CreateAppearance(Game_Pawn aPawn,export editinline Game_Appearance aAppearance,bool aShifting) {
local export editinline Game_EquippedAppearance pawnAppearance;
aAppearance = ForceAppearanceClass(aPawn,aAppearance,Class'Game_EquippedAppearance');
aAppearance = Super.CreateAppearance(aPawn,aAppearance,aShifting);          
pawnAppearance = Game_EquippedAppearance(aAppearance);                      
if (Statue) {                                                               
pawnAppearance.SetStatue(True);                                           
}
if (Ghostly) {                                                              
pawnAppearance.SetGhost(True);                                            
}
pawnAppearance.SetRace(Race);                                               
pawnAppearance.SetGender(Gender);                                           
pawnAppearance.SetBody(Bodytype);                                           
pawnAppearance.SetHead(Head);                                               
pawnAppearance.SetColorValue(21,BodyColor,0);                               
if (Hair != None) {                                                         
pawnAppearance.SetColorValue(18,HairColor,0);                             
pawnAppearance.SetValue(18,Hair._AS_Index);                               
} else {                                                                    
pawnAppearance.SetValue(18,0);                                            
}
return aAppearance;                                                         
}
*/
