//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using Engine;
using SBAI;
using SBAIScripts;
using SBBase;
using SBGame;
using SBGamePlay;
using SBMiniGames;
using System;
using System.Collections;
using System.Collections.Generic;
using Framework.Attributes;

namespace SBGamePlay
{
    
    
    [System.Serializable] public class QT_BeDefeated : Quest_Target
    {
        
        [FieldCategory(Category="Defeat")]
        [FieldConst()]
        public List<NPC_Type> NamedTargets = new List<NPC_Type>();
        
        [FieldCategory(Category="Defeat")]
        [FieldConst()]
        public List<NPC_Taxonomy> GroupedTargets = new List<NPC_Taxonomy>();
        
        [FieldCategory(Category="Defeat")]
        [FieldConst()]
        public Conversation_Topic VictorySpeech;
        
        [FieldCategory(Category="Defeat")]
        [FieldConst()]
        public float DefeatFraction;
        
        public QT_BeDefeated()
        {
        }
    }
}
