//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using Engine;
using SBAI;
using SBAIScripts;
using SBBase;
using SBGame;
using SBGamePlay;
using SBMiniGames;
using System;
using System.Collections;
using System.Collections.Generic;
using Framework.Attributes;

namespace SBGamePlay
{
    
    
    public class Spawn_Timed : Spawn_Triggered
    {
        
        [FieldCategory(Category="Spawn")]
        public float SpawnInterval;
        
        [FieldCategory(Category="Spawn")]
        public bool StopTimerIfWiped;
        
        [FieldCategory(Category="Spawn")]
        public bool OnlyStopTimerOnDespawn;
        
        public float SpawnTimer;
        
        public bool TimerStarted;
        
        public Spawn_Timed()
        {
        }
    }
}
/*
function sv_Despawn() {
if (!OnlyStopTimerOnDespawn) {                                              
Super.sv_Despawn();                                                       
}
TimerStarted = False;                                                       
SpawnTimer = 0.00000000;                                                    
}
*/
