//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using Engine;
using SBAI;
using SBAIScripts;
using SBBase;
using SBGame;
using SBGamePlay;
using SBMiniGames;
using System;
using System.Collections;
using System.Collections.Generic;
using Framework.Attributes;

namespace SBBase
{
    
    
    [System.Serializable] public class DB_Guild : Base_DBObject
    {
        
        public int GroupId;
        
        public int MotdTextId;
        
        public int LogoId;
        
        public int Color1;
        
        public int Color2;
        
        [FieldConst()]
        public List<DB_Character> mGuildMembers = new List<DB_Character>();
        
        [FieldConst()]
        public bool mGuildMembersSet;
        
        public DB_Guild()
        {
        }
    }
}
