//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using Engine;
using SBAI;
using SBAIScripts;
using SBBase;
using SBGame;
using SBGamePlay;
using SBMiniGames;
using System;
using System.Collections;
using System.Collections.Generic;
using SBAssemblies;

namespace Engine
{
    
    
    [System.Serializable] public class AnimNotify_Effect : AnimNotify
    {
        
        [Sirenix.OdinInspector.FoldoutGroup("AnimNotify_Effect")]
        [TypeProxyDefinition(TypeName="Actor")]
        public System.Type EffectClass;
        
        [Sirenix.OdinInspector.FoldoutGroup("AnimNotify_Effect")]
        public NameProperty Bone;
        
        [Sirenix.OdinInspector.FoldoutGroup("AnimNotify_Effect")]
        public Vector OffsetLocation;
        
        [Sirenix.OdinInspector.FoldoutGroup("AnimNotify_Effect")]
        public Rotator OffsetRotation;
        
        [Sirenix.OdinInspector.FoldoutGroup("AnimNotify_Effect")]
        public bool Attach;
        
        [Sirenix.OdinInspector.FoldoutGroup("AnimNotify_Effect")]
        public NameProperty Tag;
        
        [Sirenix.OdinInspector.FoldoutGroup("AnimNotify_Effect")]
        public float DrawScale;
        
        [Sirenix.OdinInspector.FoldoutGroup("AnimNotify_Effect")]
        public Vector DrawScale3D;
        
        [System.NonSerialized, UnityEngine.HideInInspector]
        [FieldTransient()]
        private Actor LastSpawnedEffect;
        
        public AnimNotify_Effect()
        {
        }
    }
}
