//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using Engine;
using SBAI;
using SBAIScripts;
using SBBase;
using SBGame;
using SBGamePlay;
using SBMiniGames;
using System;
using System.Collections;
using System.Collections.Generic;
using SBAssemblies;

namespace Engine
{
    
    
    [System.Serializable] public class MusicTrigger : Triggers
    {
        
        [Sirenix.OdinInspector.FoldoutGroup("MusicTrigger")]
        public string Song = string.Empty;
        
        [Sirenix.OdinInspector.FoldoutGroup("MusicTrigger")]
        public float FadeInTime;
        
        [Sirenix.OdinInspector.FoldoutGroup("MusicTrigger")]
        public float FadeOutTime;
        
        [Sirenix.OdinInspector.FoldoutGroup("MusicTrigger")]
        public bool FadeOutAllSongs;
        
        [System.NonSerialized, UnityEngine.HideInInspector]
        [FieldTransient()]
        public bool Triggered;
        
        [System.NonSerialized, UnityEngine.HideInInspector]
        [FieldTransient()]
        public int SongHandle;
        
        public MusicTrigger()
        {
        }
    }
}
/*
function Trigger(Actor Other,Pawn EventInstigator) {
if (!Triggered) {                                                           
Triggered = True;                                                         
if (FadeOutAllSongs) {                                                    
StopAllMusic(FadeOutTime);                                              
}
SongHandle = PlayMusic(Song,FadeInTime);                                  
} else {                                                                    
Triggered = False;                                                        
if (SongHandle != 0) {                                                    
StopMusic(SongHandle,FadeOutTime);                                      
} else {                                                                  
Log("WARNING: invalid song handle");                                    
}
}
}
*/
