//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using Engine;
using SBAI;
using SBAIScripts;
using SBBase;
using SBGame;
using SBGamePlay;
using SBMiniGames;
using System;
using System.Collections;
using System.Collections.Generic;
using Framework.Attributes;

namespace Engine
{
    
    
    public class AnimNotify_LIPSinc : AnimNotify
    {
        
        [FieldCategory(Category="AnimNotify_LIPSinc")]
        public NameProperty LIPSincAnimName;
        
        [FieldCategory(Category="AnimNotify_LIPSinc")]
        public float Volume;
        
        [FieldCategory(Category="AnimNotify_LIPSinc")]
        public int Radius;
        
        [FieldCategory(Category="AnimNotify_LIPSinc")]
        public float Pitch;
        
        public AnimNotify_LIPSinc()
        {
        }
    }
}
