//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using Engine;
using SBAI;
using SBAIScripts;
using SBBase;
using SBGame;
using SBGamePlay;
using SBMiniGames;
using System;
using System.Collections;
using System.Collections.Generic;
using Framework.Attributes;

namespace Engine
{
    
    
    public class LevelInfo : ZoneInfo
    {
        
        public float TimeDilation;
        
        [IgnoreFieldExtraction()]
        [FieldTransient()]
        public float TimeSeconds;
        
        [IgnoreFieldExtraction()]
        [FieldTransient()]
        public int Year;
        
        [IgnoreFieldExtraction()]
        [FieldTransient()]
        public int Month;
        
        [IgnoreFieldExtraction()]
        [FieldTransient()]
        public int Day;
        
        [IgnoreFieldExtraction()]
        [FieldTransient()]
        public int DayOfWeek;
        
        [IgnoreFieldExtraction()]
        [FieldTransient()]
        public int Hour;
        
        [IgnoreFieldExtraction()]
        [FieldTransient()]
        public int Minute;
        
        [IgnoreFieldExtraction()]
        [FieldTransient()]
        public int Second;
        
        [IgnoreFieldExtraction()]
        [FieldTransient()]
        public int Millisecond;
        
        [IgnoreFieldExtraction()]
        [FieldTransient()]
        [ArraySizeForExtraction(Size=4)]
        public Actor[] SunLights = new Actor[0];
        
        [IgnoreFieldExtraction()]
        [FieldTransient()]
        public int NumSunLights;
        
        public float PauseDelay;
        
        [FieldConst()]
        public float RelativeTimeOfDay;
        
        [IgnoreFieldExtraction()]
        [FieldTransient()]
        public EnvironmentManager EnvironmentManager;
        
        [FieldCategory(Category="LevelSummary")]
        public string Title = string.Empty;
        
        [FieldCategory(Category="LevelSummary")]
        public string Author = string.Empty;
        
        [FieldCategory(Category="LevelSummary")]
        public string Description = string.Empty;
        
        [FieldCategory(Category="LevelSummary")]
        [IgnoreFieldExtraction()]
        public Material Screenshot;
        
        [FieldCategory(Category="LevelSummary")]
        public string DecoTextName = string.Empty;
        
        [FieldCategory(Category="LevelSummary")]
        public int IdealPlayerCountMin;
        
        [FieldCategory(Category="LevelSummary")]
        public int IdealPlayerCountMax;
        
        [FieldCategory(Category="LevelSummary")]
        public string ExtraInfo = string.Empty;
        
        [FieldCategory(Category="SinglePlayer")]
        public int SinglePlayerTeamSize;
        
        [FieldCategory(Category="RadarMap")]
        [IgnoreFieldExtraction()]
        public Material RadarMapImage;
        
        [FieldCategory(Category="RadarMap")]
        public float CustomRadarRange;
        
        [FieldCategory(Category="LevelInfo")]
        [FieldConfig()]
        public byte PhysicsDetailLevel;
        
        [FieldCategory(Category="LevelInfo")]
        [FieldConfig()]
        public byte MeshLODDetailLevel;
        
        [FieldCategory(Category="Karma")]
        public float KarmaTimeScale;
        
        [FieldCategory(Category="Karma")]
        public float RagdollTimeScale;
        
        [FieldCategory(Category="Karma")]
        public int MaxRagdolls;
        
        [FieldCategory(Category="Karma")]
        public float KarmaGravScale;
        
        [FieldCategory(Category="Karma")]
        public bool bKStaticFriction;
        
        [FieldCategory(Category="LevelInfo")]
        public bool bKNoInit;
        
        [ArraySizeForExtraction(Size=2)]
        public int[] LastTaunt = new int[0];
        
        [FieldConfig()]
        public float DecalStayScale;
        
        [FieldCategory(Category="LevelInfo")]
        public string LevelEnterText = string.Empty;
        
        [FieldCategory(Category="LevelInfo")]
        public string LocalizedPkg = string.Empty;
        
        public LevelSummary Summary;
        
        [IgnoreFieldExtraction()]
        [FieldTransient()]
        public string VisibleGroups = string.Empty;
        
        [FieldCategory(Category="LevelSummary")]
        public bool HideFromMenus;
        
        [FieldCategory(Category="LevelInfo")]
        public bool bLonePlayer;
        
        public bool bBegunPlay;
        
        public bool bPlayersOnly;
        
        public bool bFreezeKarma;
        
        [FieldConst()]
        public byte DetailMode;
        
        public bool bDropDetail;
        
        public bool bAggressiveLOD;
        
        public bool bStartup;
        
        [FieldConfig()]
        public bool bLowSoundDetail;
        
        public bool bPathsRebuilt;
        
        public bool bHasPathNodes;
        
        public bool bLevelChange;
        
        public bool bShouldPreload;
        
        public bool bDesireSkinPreload;
        
        public bool bKickLiveIdlers;
        
        public bool bSkinsPreloaded;
        
        public bool bClassicView;
        
        [FieldCategory(Category="RadarMap")]
        public bool bShowRadarMap;
        
        [FieldCategory(Category="RadarMap")]
        public bool bUseTerrainForRadarRange;
        
        public bool bIsSaveGame;
        
        [FieldCategory(Category="SaveGames")]
        public bool bSupportSaveGames;
        
        [FieldConfig()]
        public bool bNeverPrecache;
        
        [FieldCategory(Category="LevelInfo")]
        public int LevelTextureLODBias;
        
        public float AnimMeshGlobalLOD;
        
        [FieldCategory(Category="LevelInfo")]
        public Vector CameraLocationDynamic;
        
        [FieldCategory(Category="LevelInfo")]
        public Vector CameraLocationTop;
        
        [FieldCategory(Category="LevelInfo")]
        public Vector CameraLocationFront;
        
        [FieldCategory(Category="LevelInfo")]
        public Vector CameraLocationSide;
        
        [FieldCategory(Category="LevelInfo")]
        public Rotator CameraRotationDynamic;
        
        [FieldCategory(Category="Audio")]
        public string Song = string.Empty;
        
        [FieldCategory(Category="Audio")]
        public float PlayerDoppler;
        
        [FieldCategory(Category="Audio")]
        public float MusicVolumeOverride;
        
        [FieldCategory(Category="LevelInfo")]
        public float Brightness;
        
        [IgnoreFieldExtraction()]
        public string DefaultTexture; //texture
        
        [IgnoreFieldExtraction()]
        public string WireframeTexture;//texture
        
        [IgnoreFieldExtraction()]
        public string WhiteSquareTexture;//texture
        
        [IgnoreFieldExtraction()]
        public string LargeVertex;
        
        public int HubStackLevel;
        
        [IgnoreFieldExtraction()]
        [FieldTransient()]
        public byte LevelAction;
        
        public byte NetMode;
        
        public string ComputerName = string.Empty;
        
        public string EngineVersion = string.Empty;
        
        public string MinNetVersion = string.Empty;
        
        [FieldCategory(Category="LevelInfo")]
        public string DefaultGameType = string.Empty;
        
        [FieldCategory(Category="LevelInfo")]
        public string PreCacheGame = string.Empty;
        
        public float DefaultGravity;
        
        public float LastVehicleCheck;
        
        [FieldCategory(Category="LevelInfo")]
        public float StallZ;
        
        [FieldConst()]
        public NavigationPoint NavigationPointList;
        
        [FieldConst()]
        public Controller ControllerList;
        
        [FieldCategory(Category="Headlights")]
        public bool bUseHeadlights;
        
        [FieldCategory(Category="Headlights")]
        public float HeadlightScaling;
        
        public string NextURL = string.Empty;
        
        public bool bNextItems;
        
        public float NextSwitchCountdown;
        
        [IgnoreFieldExtraction()]
        [FieldTransient()]
        public ObjectPool ObjectPool;
        
        [IgnoreFieldExtraction()]
        [FieldTransient()]
        public List<Material> PrecacheMaterials = new List<Material>();
        
        [IgnoreFieldExtraction()]
        [FieldTransient()]
        public List<StaticMesh> PrecacheStaticMeshes = new List<StaticMesh>();
        
        [FieldCategory(Category="Camouflage")]
        [IgnoreFieldExtraction()]
        public StaticMesh IndoorCamouflageMesh;
        
        [FieldCategory(Category="Camouflage")]
        public float IndoorMeshDrawscale;
        
        [FieldCategory(Category="Camouflage")]
        [IgnoreFieldExtraction()]
        public StaticMesh OutdoorCamouflageMesh;
        
        [FieldCategory(Category="Camouflage")]
        public float OutdoorMeshDrawscale;
        
        [FieldCategory(Category="DustColor")]
        [IgnoreFieldExtraction()]
        public Color DustColor;
        
        [FieldCategory(Category="DustColor")]
        [IgnoreFieldExtraction()]
        public Color WaterDustColor;
        
        public float MoveRepSize;
        
        public float MaxClientFrameRate;
        
        public float MaxTimeMargin;
        
        public float TimeMarginSlack;
        
        public float MinTimeMargin;
        
        [FieldConst()]
        public PlayerController ReplicationViewer;
        
        [FieldConst()]
        public Actor ReplicationViewTarget;
        
        [FieldConst()]
        [IgnoreFieldExtraction()]
        [FieldTransient()]
        public string LightingCubeMap; //SBLightingCubemap
        
        public LevelInfo()
        {
        }
        
        public enum ENetMode
        {
            
            NM_Standalone ,
            
            NM_DedicatedServer ,
            
            NM_ListenServer ,
            
            NM_Client,
        }
        
        public enum ELevelAction
        {
            
            LEVACT_None ,
            
            LEVACT_Loading ,
            
            LEVACT_Saving ,
            
            LEVACT_Connecting ,
            
            LEVACT_Precaching,
        }
        
        public enum EMeshLODDetailLevel
        {
            
            MDL_Low ,
            
            MDL_Medium ,
            
            MDL_High ,
            
            MDL_Ultra,
        }
        
        public enum EPhysicsDetailLevel
        {
            
            PDL_Low ,
            
            PDL_Medium ,
            
            PDL_High,
        }
    }
}
/*
native function EnvironmentManager GetEnvironmentManager();
function ObjectPool GetObjectPool() {
if (ObjectPool == None) {                                                   
ObjectPool = new (XLevel) Class'ObjectPool';                              
}
return ObjectPool;                                                          
}
native function PlayerController GetLocalPlayerController();
simulated event PreBeginPlay() {
Super.PreBeginPlay();                                                       
ObjectPool = new (XLevel) Class'ObjectPool';                                
}
function Reset() {
DefaultGravity = default.DefaultGravity;                                    
Super.Reset();                                                              
}
function ThisIsNeverExecuted() {
local DefaultPhysicsVolume P;
P = None;                                                                   
}
event ServerTravel(string URL,bool bItems) {
}
native simulated function string GetAddressURL();
final static native function bool IsSoftwareRendering();
final static native function bool IsDemoBuild();
native simulated function string GetLocalURL();
simulated function AddPrecacheStaticMesh(StaticMesh stat) {
local int Index;
if (NetMode == 1) {                                                         
return;                                                                   
}
if (stat == None) {                                                         
return;                                                                   
}
Log("Adding static mesh to precache array: "
$ string(stat));         
Index = Level.PrecacheStaticMeshes.Length;                                  
PrecacheStaticMeshes.Insert(Index,1);                                       
PrecacheStaticMeshes[Index] = stat;                                         
}
simulated function AddPrecacheMaterial(Material mat) {
local int Index;
if (NetMode == 1) {                                                         
return;                                                                   
}
if (mat == None) {                                                          
return;                                                                   
}
Index = Level.PrecacheMaterials.Length;                                     
PrecacheMaterials.Insert(Index,1);                                          
PrecacheMaterials[Index] = mat;                                             
}
simulated event FillPrecacheStaticMeshesArray(bool FullPrecache) {
local Actor A;
if (NetMode == 1) {                                                         
return;                                                                   
}
Log("Starting search for uncached static meshes");                          
foreach AllActors(Class'Actor',A) {                                         
if (!A.bAlreadyPrecachedMeshes || FullPrecache) {                         
A.UpdatePrecacheStaticMeshes();                                         
A.bAlreadyPrecachedMeshes = True;                                       
}
}
Log("Ending search");                                                       
}
simulated function PrecacheAnnouncements();
simulated event FillPrecacheMaterialsArray(bool FullPrecache) {
local Actor A;
if (NetMode == 1) {                                                         
return;                                                                   
}
if (!bSkinsPreloaded || FullPrecache) {                                     
}
foreach AllActors(Class'Actor',A) {                                         
if (!A.bAlreadyPrecachedMaterials || FullPrecache) {                      
A.UpdatePrecacheMaterials();                                            
A.bAlreadyPrecachedMaterials = True;                                    
}
}
}
simulated function PostBeginPlay() {
Super.PostBeginPlay();                                                      
DecalStayScale = Max(DecalStayScale,0);                                     
}
native simulated function PhysicsVolume GetPhysicsVolume(Vector loc);
native simulated function ForceLoadTexture(Texture Texture);
native simulated function UpdateDistanceFogLOD(float LOD);
native simulated function byte GetDetailMode();
native simulated function DetailChange(byte NewDetailMode);
*/
