//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

using Engine;
using SBAI;
using SBAIScripts;
using SBBase;
using SBGame;
using SBGamePlay;
using SBMiniGames;
using System;
using System.Collections;
using System.Collections.Generic;
using Framework.Attributes;

namespace Engine
{
    
    
    public class Material : UObject
    {
        
        [FieldCategory(Category="Material")]
        [IgnoreFieldExtraction()]
        public Material FallbackMaterial;
        
        [IgnoreFieldExtraction()]
        public Material DefaultMaterial;
        
        [FieldConst()]
        [IgnoreFieldExtraction()]
        [FieldTransient()]
        public bool UseFallback;
        
        [FieldConst()]
        [IgnoreFieldExtraction()]
        [FieldTransient()]
        public bool Validated;
        
        [FieldCategory(Category="Material")]
        public Actor.ESurfaceTypes SurfaceType;
        
        public int MaterialType;
        
        public Material()
        {
        }
    }
}
/*
native function int MaterialVSize();
native function int MaterialUSize();
function Trigger(Actor Other,Actor EventInstigator) {
if (FallbackMaterial != None) {                                             
FallbackMaterial.Trigger(Other,EventInstigator);                          
}
}
function Reset() {
if (FallbackMaterial != None) {                                             
FallbackMaterial.Reset();                                                 
}
}
*/
